### ISSUE TITLE
Fauxpen source

### ISSUE THREAD

**Issue by flatsiedatsie** [Standard-Intelligence/hertz-dev#8]
You seem to refer to your creation as `open source`, but I believe that "open weights" would be a fairer asssement? Since you haven't open sourced the training data, for example.

Happy to be wrong!

**Comment by twilligon** [comment]
Thanks for asking about this—I hate dubiously "open-source" licenses as much as anyone. We consider this release of `hertz-dev` to meet the OSI's [Open Source Definition](https://opensource.org/osd). All of our code and weights are released under the Apache 2.0 license, allowing free redistribution and derived works without discrimination against persons, groups, or fields of endeavor and without restriction to use with or without specific products. The most open-to-interpretation point is how the point on source code applies to weights:

> The program must include source code, and must allow distribution in source code as well as compiled form. Where some form of a product is not distributed with source code, there must be a well-publicized means of obtaining the source code for no more than a reasonable reproduction cost, preferably downloading via the Internet without charge. **The source code must be the preferred form in which a programmer would modify the program.** Deliberately obfuscated source code is not allowed. Intermediate forms such as the output of a preprocessor or translator are not allowed.

The `hertz-dev` weights are "the preferred form in which a programmer would modify the program": base models are valuable because they can be fine-tuned to do specific tasks. On the other hand, the training data is less useful for extending and modifying `hertz-dev`. We're happy to provide a full codebase, model checkpoint, and [architecture details](https://si.inc/hertz-dev/) to make this possible.
